services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - '8080'
      - '5432'
    ports:
      - '5432:5432'
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'nakama']
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    build: ./src/nakama
    container_name: nakama
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --name nakama --database.address postgres:localdb@postgres:5432/nakama
    restart: always
    links:
      - 'postgres:db'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/nakama/local.yml:/nakama/data/local.yml
    expose:
      - '7349'
      - '7350'
      - '7351'
    ports:
      - '7349:7349'
      - '7350:7350'
      - '7351:7351'
    healthcheck:
      test: ['CMD', '/nakama/nakama', 'healthcheck']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: docker.io/bitnami/redis:8.2.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  data:
  redis_data:
    driver: local
