package types

type Skill string

const (
	SkillAdaptable            Skill = "skill.adaptable"
	SkillAgile                Skill = "skill.agile"
	SkillArtisan              Skill = "skill.artisan"
	SkillAviator              Skill = "skill.aviator"
	SkillBotanist             Skill = "skill.botanist"
	SkillCombatMedic          Skill = "skill.combat-medic"
	SkillCommsSavvy           Skill = "skill.comms-savvy"
	SkillCook                 Skill = "skill.cook"
	SkillDemolition           Skill = "skill.demolition"
	SkillDiligent             Skill = "skill.diligent"
	SkillEngineer             Skill = "skill.engineer"
	SkillExperiencedCommander Skill = "skill.experienced-commander"
	SkillGunsFundamental      Skill = "skill.guns-fundamental"
	SkillInfantry             Skill = "skill.infantry"
	SkillLogistician          Skill = "skill.logistician"
	SkillMechpilot            Skill = "skill.mechpilot"
	SkillPersuasion           Skill = "skill.persuasion"
	SkillPharmacologist       Skill = "skill.pharmacologist"
	SkillPhysician            Skill = "skill.physician"
	SkillPilot                Skill = "skill.pilot"
	SkillPirate               Skill = "skill.pirate"
	SkillProdigyLeader        Skill = "skill.prodigy-leader"
	SkillProtector            Skill = "skill.protector"
	SkillSavant               Skill = "skill.savant"
	SkillShooter              Skill = "skill.shooter"
	SkillSilver               Skill = "skill.silver"
	SkillSniper               Skill = "skill.sniper"
	SkillStalwart             Skill = "skill.stalwart"
	SkillSurgeon              Skill = "skill.surgeon"
	SkillTactician            Skill = "skill.tactician"
	SkillTechnician           Skill = "skill.technician"
	SkillTriarii              Skill = "skill.triarii"
	SkillVisionary            Skill = "skill.visionary"
)
