import type { SupersectorNames } from '@nanosh/types/sectors'
import type { Trader } from '@nanosh/types/trader'

export const Traders = new Map<SupersectorNames, Trader[]>([
  [
    'Arctic Circle',
    [
      {
        name: 'Northern Barterers',
        given: 'supplies',
        minGiven: 17,
        maxGiven: 23,
        taken: 'rations',
        minTaken: 15,
        maxTaken: 15,
      },
      {
        name: 'Glacial Provisioners',
        given: 'supplies',
        minGiven: 12,
        maxGiven: 18,
        taken: 'eCells',
        minTaken: 2,
        maxTaken: 2,
      },
    ],
  ],
  [
    'European Federation',
    [
      {
        name: 'The Desperate Collectors',
        given: 'supplies',
        minGiven: 27,
        maxGiven: 33,
        taken: 'rations',
        minTaken: 20,
        maxTaken: 20,
      },
      {
        name: 'Continental Connectors',
        given: 'rations',
        minGiven: 12,
        maxGiven: 18,
        taken: 'supplies',
        minTaken: 25,
        maxTaken: 25,
      },
    ],
  ],
  [
    'RUSSE-CAN',
    [
      {
        name: 'Siberian Suppliers',
        given: 'supplies',
        minGiven: 21,
        maxGiven: 27,
        taken: 'rations',
        minTaken: 16,
        maxTaken: 16,
      },
      {
        name: 'Frost Frontier Vendors',
        given: 'supplies',
        minGiven: 17,
        maxGiven: 23,
        taken: 'eCells',
        minTaken: 3,
        maxTaken: 3,
      },
    ],
  ],
  [
    'East Asia Enclave',
    [
      {
        name: 'Red Party Innovators',
        given: 'supplies',
        minGiven: 21,
        maxGiven: 27,
        taken: 'rations',
        minTaken: 16,
        maxTaken: 16,
      },
      {
        name: 'Neonblade Networkers',
        given: 'rations',
        minGiven: 12,
        maxGiven: 18,
        taken: 'eCells',
        minTaken: 10,
        maxTaken: 10,
      },
    ],
  ],
  [
    'North American Union',
    [
      {
        name: 'Siberian Suppliers',
        given: 'supplies',
        minGiven: 21,
        maxGiven: 27,
        taken: 'rations',
        minTaken: 16,
        maxTaken: 16,
      },
      {
        name: 'Frost Frontier Vendors',
        given: 'supplies',
        minGiven: 17,
        maxGiven: 23,
        taken: 'eCells',
        minTaken: 3,
        maxTaken: 3,
      },
    ],
  ],
  [
    'MENA Coalition',
    [
      {
        name: 'Gold Sphinx Dealers',
        given: 'supplies',
        minGiven: 21,
        maxGiven: 27,
        taken: 'rations',
        minTaken: 16,
        maxTaken: 16,
      },
      {
        name: 'The Mighty Oasis Peddler',
        given: 'rations',
        minGiven: 15,
        maxGiven: 21,
        taken: 'eCells',
        minTaken: 12,
        maxTaken: 12,
      },
    ],
  ],
  [
    'South Asian Network',
    [
      {
        name: 'Ceylon Traders',
        given: 'supplies',
        minGiven: 22,
        maxGiven: 28,
        taken: 'eCells',
        minTaken: 3,
        maxTaken: 3,
      },
      {
        name: 'Monsoon Flying Market',
        given: 'rations',
        minGiven: 7,
        maxGiven: 13,
        taken: 'supplies',
        minTaken: 15,
        maxTaken: 15,
      },
    ],
  ],
  [
    'SEA Bloc',
    [
      {
        name: 'The Archipelago Hailers',
        given: 'supplies',
        minGiven: 12,
        maxGiven: 18,
        taken: 'rations',
        minTaken: 16,
        maxTaken: 16,
      },
      {
        name: 'Indonesian Fishermen',
        given: 'rations',
        minGiven: 17,
        maxGiven: 23,
        taken: 'eCells',
        minTaken: 3,
        maxTaken: 3,
      },
    ],
  ],
  [
    'South American Alliance',
    [
      {
        name: 'Albonaldo Supply Co.',
        given: 'supplies',
        minGiven: 27,
        maxGiven: 33,
        taken: 'eCells',
        minTaken: 4,
        maxTaken: 4,
      },
      {
        name: 'Amazonian Warmaidens',
        given: 'rations',
        minGiven: 22,
        maxGiven: 28,
        taken: 'eCells',
        minTaken: 3,
        maxTaken: 3,
        items: new Set([
          { minGiven: 3, maxGiven: 8, itemName: 'food.glownana' },
        ]),
      },
    ],
  ],
  [
    'South African Confederation',
    [
      {
        name: 'Savannah Supliers',
        given: 'supplies',
        minGiven: 17,
        maxGiven: 23,
        taken: 'rations',
        minTaken: 15,
        maxTaken: 15,
      },
      {
        name: 'Kalahari Express',
        given: 'eCells',
        minGiven: 3,
        maxGiven: 3,
        taken: 'rations',
        minTaken: 27,
        maxTaken: 33,
      },
    ],
  ],
  [
    'Oceanian Front',
    [
      {
        name: 'Outback Outfitters',
        given: 'supplies',
        minGiven: 22,
        maxGiven: 28,
        taken: 'eCells',
        minTaken: 4,
        maxTaken: 4,
      },
      {
        name: 'Pacific Provisioners',
        given: 'eCells',
        minGiven: 3,
        maxGiven: 3,
        taken: 'rations',
        minTaken: 17,
        maxTaken: 23,
      },
    ],
  ],
  [
    'Antarctic Pole',
    [
      {
        name: 'The Polar Logistics',
        given: 'supplies',
        minGiven: 12,
        maxGiven: 18,
        taken: 'eCells',
        minTaken: 2,
        maxTaken: 2,
      },
      {
        name: 'Ice Cap One Stop',
        given: 'rations',
        minGiven: 12,
        maxGiven: 18,
        taken: 'eCells',
        minTaken: 2,
        maxTaken: 2,
      },
    ],
  ],
])
