export type Traits =
  | 'trait.ace'
  | 'trait.amorous'
  | 'trait.calm'
  | 'trait.defender'
  | 'trait.driven'
  | 'trait.droid'
  | 'trait.dutiful'
  | 'trait.gung-ho'
  | 'trait.hardworking'
  | 'trait.legatus-legionis'
  | 'trait.meticulous'
  | 'trait.popular'
  | 'trait.regenesis'
